### ISSUE TITLE
Transfer project's ownership

### ISSUE THREAD

**Issue by rigwild** [martinj/node-apidoc-markdown#12]
This repository is not maintained, it contains highly vulnerable dependencies (EJS very old version), old JavaScript syntax and no new features (including new apiDoc specs).

I updated all of this in [my fork](https://github.com/rigwild/apidoc-markdown). I'm willing to maintain it, adding new features and answer to issues/PR.
I suggest that this repository transfer ownership or mention the updated version in the README.
@martinj 
Love the work!

**Comment by martinj** [comment]
Awesome! Updated the readme with link to your fork.
