### ISSUE TITLE
Transfer npm package

### ISSUE THREAD

**Issue by rigwild** [martinj/node-apidoc-markdown#13]
Hi,

It's been a year since you set the notice to go to the forked version, thanks again. It is still maintained as of now.

Would you agree to transfer your [npm package](https://www.npmjs.com/package/apidoc-markdown) to me ? It would help to get my version more used.

If you are ok, I will do the following:
 - Fully deprecate [@rigwild/apidoc-markdown](https://www.npmjs.com/package/@rigwild/apidoc-markdown) with a notice do go grab the new package.
 - Deprecate current versions of [apidoc-markdown](https://www.npmjs.com/package/apidoc-markdown) with a notice to upgrade to the newest version
 - Upgrade [apidoc-markdown](https://www.npmjs.com/package/apidoc-markdown) to the last version of [@rigwild/apidoc-markdown](https://www.npmjs.com/package/@rigwild/apidoc-markdown) and continue maintaining it (see https://github.com/rigwild/apidoc-markdown).

See https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account.

Thanks!

**Comment by martinj** [comment]
Added you as maintainer let me know when you have verified access to it and i'll remove my self as maintainer.

**Comment by rigwild** [comment]
Done! Thanks a lot :relaxed:
